In [1]:
import numpy as np

In [4]:
A=np.arange(15).reshape(3,5)
B=np.arange(10).reshape(5,2)
M=np.empty((3,2))
print(A)
print(B)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [5]:
ein=np.einsum('ij,jk->ik',A,B)
ein

array([[ 60,  70],
       [160, 195],
       [260, 320]])

In [7]:
for i in range(3):
    for j in range(2):
        total=0
        for k in range(5):
            total+=A[i,k]*B[k,j]
        M[i,j]=total
M

array([[ 60.,  70.],
       [160., 195.],
       [260., 320.]])

In [8]:
np.einsum('ij,ij->ij',B,B)

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49],
       [64, 81]])